#@ load("@ytt:data", "data")
#@ load("@ytt:overlay", "overlay")

#@overlay/match by=overlay.subset({"kind":"DaemonSet", "metadata": {"name": "fluent-bit"}}), expects=1
---
spec:
  updateStrategy: #@ data.values.fluent_bit.daemonset.updateStrategy
  template:
    metadata:
      labels: #@ data.values.fluent_bit.daemonset.podLabels
      annotations: #@ data.values.fluent_bit.daemonset.podAnnotations
    spec:
      containers:
       #@overlay/match by="name"
        - name: fluent-bit
          resources: #@ data.values.fluent_bit.daemonset.resources
