#@ load("@ytt:data", "data")
---
apiVersion: velero.io/v1
kind: VolumeSnapshotLocation
metadata:
  labels:
    component: velero
  name: #@ data.values.volumeSnapshotLocation.name
  namespace: #@ data.values.namespace
spec:
  provider: #@ data.values.provider
  config:
    region: #@ data.values.volumeSnapshotLocation.aws.region