apiVersion: packaging.carvel.dev/v1alpha1
kind: PackageInstall
metadata:
  name: my-cert-manager
  namespace: cert-manager
spec:
  serviceAccountName: cert-manager-sa
  packageRef:
    refName: cert-manager.community.tanzu.vmware.com
    versionSelection:
      constraints: ">=1.0.0"
