#@ load("@ytt:data", "data")
---
#@ if data.values.provider == 'minio':
apiVersion: v1
kind: Secret
metadata:
  labels:
    component: velero
  name: cloud-credentials
  namespace: velero
#@yaml/text-templated-strings
stringData:
  cloud: |
    [default]
    aws_access_key_id = (@= data.values.minio.accessKey @)
    aws_secret_access_key = (@= data.values.minio.secretKey @)
type: Opaque
#@ end
