#@ load("@ytt:data", "data")
---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  labels:
    component: velero
  name: default
  namespace: velero
spec:
  config:
    region: #@ data.values.defaultBackupStorageLocation.region
    #@ if data.values.minio.enabled:
    s3ForcePathStyle: "true"
    s3Url: http://minio.velero.svc:9000
    #@ end
  objectStorage:
    bucket: #@ data.values.defaultBackupStorageLocation.bucket
  provider: #@ data.values.provider