#@ load("@ytt:data", "data")
---
apiVersion: velero.io/v1
kind: BackupStorageLocation
metadata:
  labels:
    component: velero
  name: #@ data.values.backupStorageLocation.name
  namespace: velero
spec:
  provider: #@ data.values.provider
  objectStorage:
    bucket: #@ data.values.backupStorageLocation.bucket
  config:
    region: #@ data.values.backupStorageLocation.aws.region
    #@ if data.values.minio.enabled:
    s3ForcePathStyle: "true"
    s3Url: http://minio.velero.svc:9000
    #@ end