apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: contour.community.tanzu.vmware.com.1.0.0
  namespace: contour
spec:
  refName: contour.community.tanzu.vmware.com
  version: 1.0.0
  releaseNotes: "contour 1.15.1 https://github.com/projectcontour/contour/releases/tag/v1.15.1"
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/contour@sha256:c75d3441a7cb136cbbb381d037fe4ea039eefe3d0bd93d7317bf78db776c374c
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
