apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: PACKAGE_NAME.community.tanzu.vmware.com.1.0.0
  namespace: PACKAGE_NAME
spec:
  refName: PACKAGE_NAME.community.tanzu.vmware.com
  version: 1.0.0
  releaseNotes: "PACKAGE_NAME VERSION RELEASE_NOTES_URL"
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry...
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
