apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: fluent-bit.community.tanzu.vmware.com.1.0.0
  namespace: fluent-bit
spec:
  refName: fluent-bit.community.tanzu.vmware.com
  version: 1.0.0
  releaseNotes: "fluent-bit 1.7.4 https://github.com/fluent/fluent-bit/releases/tag/v1.7.4"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/fluent-bit@sha256:c0baf2878e54c232ad33fc815a876048e9643633c8081c3c720998d560357961
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
