apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: vsphere-csi.community.tanzu.vmware.com.2.1.0
  namespace: vsphere-csi
spec:
  refName: vsphere-csi.community.tanzu.vmware.com
  version: 2.1.0
  releaseNotes: "vsphere-csi 2.1.0 https://github.com/kubernetes-sigs/vsphere-csi-driver/releases/tag/v2.1.0"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/vsphere-csi@sha256:a7e8e077dccb2580bdef57553ee0817950534fe1fb164b65abf07f0c97b31c34
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
