apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: fluent-bit.community.tanzu.vmware.com.1.7.5
  namespace: fluent-bit
spec:
  refName: fluent-bit.community.tanzu.vmware.com
  version: 1.7.5
  releaseNotes: "fluent-bit 1.7.4 https://github.com/fluent/fluent-bit/releases/tag/v1.7.5"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/fluent-bit@sha256:dfafd1d55cf0e8c9aefb70b1b26101b3241cfb414484c1f43a7aa4568cde39ae
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
