apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: contour-operator.community.tanzu.vmware.com.1.15.1
  namespace: contour-operator
spec:
  refName: contour-operator.community.tanzu.vmware.com
  version: 1.15.1
  releaseNotes: "contour-operator 1.15.1 https://github.com/projectcontour/contour/releases/tag/v1.15.1"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/contour-operator@sha256:30e4ee85167ec47e3492bfdf02f42745e8c326f6314c6f7bd52be4974f613c6a
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
