apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: load-balancer-and-ingress-service.community.tanzu.vmware.com.1.0.0
  namespace: load-balancer-and-ingress-service
spec:
  refName: load-balancer-and-ingress-service.community.tanzu.vmware.com
  version: 1.0.0
  releaseNotes: "load-balancer-and-ingress-service 1.3.1"
  licenses:
    - "UNKNOWN"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/load-balancer-and-ingress-service@sha256:fd17e7ac0a3a9b39ac65779e59ca62cdbeb557e1b0b3ab8c56d2c59b2085005d
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
