apiVersion: v1
kind: ServiceAccount
metadata:
  name: velero-extension-sa
  namespace: tanzu-extensions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: velero-extension
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: velero-extension-sa
    namespace: tanzu-extensions
---
apiVersion: kappctrl.k14s.io/v1alpha1
kind: App
metadata:
  name: velero
  namespace: tanzu-extensions
spec:
  syncPeriod: 5m
  serviceAccountName: velero-extension-sa
  fetch:
    - bundle:
        url: projects.registry.vmware.com/tce/velero-extension-templates:dev
  template:
    - ytt: 
        ignoreUnknownComments: true
        paths:
          - config
        inline:
          paths:
            values.yaml: |
              #@data/values
              ---
              provider: aws
              backupStorageLocation:
                bucket: tce-velero
                aws:
                  region: us-east-2
              volumeSnapshotLocation:
                aws:
                  region: us-east-2
    - kbld: {}
  deploy:
    - kapp:
        rawOptions: ["--wait-timeout=5m"]
