apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: external-dns.community.tanzu.vmware.com.1.0.0
  namespace: external-dns
spec:
  refName: external-dns.community.tanzu.vmware.com
  version: 1.0.0
  releaseNotes: "external-dns 0.80.0 https://github.com/kubernetes-sigs/external-dns/releases/tag/v0.8.0"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/external-dns@sha256:fe2c6bd55910fa8353e6a7f65706850a59fe78a3015eddbf2df2bfa0853662ff
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
