#@ load("@ytt:data", "data")
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    control-plane: contour-operator
  name: contour-operator
  namespace: #@ data.values.namespace
spec:
  replicas: #@ data.values.deployment.replicas
  selector:
    matchLabels:
      control-plane: contour-operator
  template:
    metadata:
      labels:
        control-plane: contour-operator
    spec:
      containers:
        - args:
            - --secure-listen-address=0.0.0.0:8443
            - --upstream=http://127.0.0.1:8080/
            - --logtostderr=true
            - --v=10
          image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
          name: kube-rbac-proxy
          ports:
            - containerPort: 8443
              name: https
        - args:
            - --metrics-addr=127.0.0.1:8080
            - --enable-leader-election
          command:
            - /contour-operator
            - --contour-image
            - docker.io/projectcontour/contour:v1.11.0
            - --envoy-image
            - docker.io/envoyproxy/envoy:v1.16.2
          image: docker.io/projectcontour/contour-operator:v1.11.0
          imagePullPolicy: IfNotPresent
          name: contour-operator
          resources:
            requests:
              cpu: #@ data.values.deployment.containers.resources.requests.cpu
              memory: #@ data.values.deployment.containers.resources.requests.memory
      terminationGracePeriodSeconds: 10
