#@ load("@ytt:data", "data")
---
apiVersion: v1
kind: Secret
metadata:
  labels:
    gatekeeper.sh/system: "yes"
  annotations:
    kapp.k14s.io/change-group: "tce.gatekeeper/secret"
  name: gatekeeper-webhook-server-cert
  namespace: #@ data.values.namespace
