apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: harbor.community.tanzu.vmware.com.1.0.0
  namespace: harbor
spec:
  refName: harbor.community.tanzu.vmware.com
  version: 1.0.0
  releaseNotes: "harbor 2.2.2 https://github.com/goharbor/harbor/releases/tag/v2.2.2"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/harbor@sha256:8559aa635048d8260b8280fcd2560244de22f0c9b9ed009f5c1d84379339f7d0
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
