apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: contour-operator.community.tanzu.vmware.com.1.1.0
  namespace: contour-operator
spec:
  refName: contour-operator.community.tanzu.vmware.com
  version: 1.1.0
  releaseNotes: "contour-operator 1.16.0 https://github.com/projectcontour/contour/releases/tag/v1.16.0"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/contour-operator@sha256:e84acdba1e86272a91129875583f3e7902164d9e831a01d78847ddc0c2cf5384
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
