apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: multus-cni.community.tanzu.vmware.com.3.7.1
  namespace: multus-cni
spec:
  refName: multus-cni.community.tanzu.vmware.com
  version: 3.7.1
  releaseNotes: "multus-cni 3.7.1 https://github.com/k8snetworkplumbingwg/multus-cni/releases/tag/v3.7.1"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/multus-cni@sha256:d60722bfbc865cb61faee1115455806af7b5a25f2224ed7031a6411fb62c76a9
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
