apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: cert-manager.community.tanzu.vmware.com.1.0.0
  namespace: cert-manager
spec:
  refName: cert-manager.community.tanzu.vmware.com
  version: 1.0.0
  releaseNotes: "cert-manager 1.3.1 https://github.com/jetstack/cert-manager/releases/tag/v1.3.1"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/cert-manager@sha256:61d43ccbe21b2e1954bb9cb3f5a024e0aa2624d8372157ca9c794d4fd0a74b6b
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
