apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: local-path-storage.community.tanzu.vmware.com.1.0.0
  namespace: local-path-storage
spec:
  refName: local-path-storage.community.tanzu.vmware.com
  version: 1.0.0
  releaseNotes: "local-path-storage 0.0.19 https://github.com/rancher/local-path-provisioner/releases/tag/v0.0.19"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/local-path-storage@sha256:19d3e633cd2b614b290dca8159eac76d75dc74b10d232037ec735b46d04d77e9
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - .imgpkg/images.yml
      deploy:
        - kapp: {}
