name: Check lint

on:
  pull_request:
    types:
      - assigned
      - opened
      - synchronize
      - reopened
    paths:
    - '**.go'
    - 'hack/check-lint.sh'

jobs:

  checklint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Config credentials
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        git config --global url."https://git:$GH_ACCESS_TOKEN@github.com".insteadOf "https://github.com"

    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v2
      with:
        version: v1.38.0
        args: --timeout=5m -v
