name: PR check shell

on:
  pull_request:
    paths:
    - '**.sh'
    - 'hack/check-shell.sh'

jobs:

  shell:
    name: Check shell
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run shellcheck
      run: |
        make shellcheck
