name: PR check vet

on:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
    paths:
    - '**.go'
    - 'hack/check-vet.sh'

jobs:

  vet:
    name: Check vet
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Run vet
      run: |
        make vet
