name: Create Release

on:
  push:
    tags:
      - 'v*'
    branches:
      - main

jobs:

  build:
    name: Release
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: '1.15'
      id: go

    - name: Config credentials
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: |
        git config --global url."https://git:$GH_ACCESS_TOKEN@github.com".insteadOf "https://github.com"

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1

    - name: Get dependencies
      run: |
        go get -v -t -d ./...

    - name: Generate release
      env:
        GH_ACCESS_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      run: make release

    - name: Test
      run: make test

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        body: |
          Changelog:
          - TODO: First Change
          - TODO: Second Change
        draft: true
        prerelease: false

    - name: Upload Linux AMD64 Asset
      id: upload-linux-amd64-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/tce-linux-amd64-${{ github.ref }}.tar.gz
        asset_name: tce-linux-amd64-${{ github.ref }}.tar.gz
        asset_content_type: application/gzip

    - name: Upload Darwin AMD64 Asset
      id: upload-darwin-amd64-asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GH_ACCESS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./build/tce-darwin-amd64-${{ github.ref }}.tar.gz
        asset_name: tce-darwin-amd64-${{ github.ref }}.tar.gz
        asset_content_type: application/gzip

    - id: upload-artifacts-staging
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: ./artifacts
        destination: tce-cli-plugins-staging
        credentials: ${{ secrets.GCP_BUCKET_SA }}

    - id: upload-metadata-staging
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: ./metadata
        destination: tce-cli-plugins-staging
        credentials: ${{ secrets.GCP_BUCKET_SA }}

    - id: upload-artifacts-release
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: ./artifacts
        destination: tce-cli-plugins
        credentials: ${{ secrets.GCP_BUCKET_SA }}

    - id: upload-metadata-release
      uses: google-github-actions/upload-cloud-storage@main
      with:
        path: ./metadata
        destination: tce-cli-plugins
        credentials: ${{ secrets.GCP_BUCKET_SA }}
